### ISSUE TITLE
repo detail page support?

### ISSUE THREAD

**Issue by lucasjinreal** [huangyanxiong01/Github-Trending-App#1]
does it plan support detail page?

**Comment by myfreax** [comment]
The details page is in the plan.I want to make it a simple tour of github trending, then let the user add stars and see the warehouse where I have added stars.

**Comment by lucasjinreal** [comment]
@huangyanxiong01  Waiting for your updates... BTW, using markdown parse rather than flutter_webview is more good since flutter_webview can not work well on iOS

**Comment by myfreax** [comment]
@jinfagang Thank you for your suggestion, I originally intended to use the webview to explain the readme.md
